services:
  - type: web
    name: spin-earn-server
    env: node
    plan: free
    buildCommand: npm ci && npm run build
    startCommand: npm start
    healthCheckPath: /healthz
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 8080
      - key: MONGODB_URI
        sync: false
      - key: JWT_ACCESS_SECRET
        sync: false
      - key: JWT_REFRESH_SECRET
        sync: false
      - key: ALLOWED_ORIGINS
        sync: false
      - key: SSV_SHARED_SECRET
        sync: false
      - key: ADMOB_APP_ID_ANDROID
        sync: false
      - key: ADMOB_APP_ID_IOS
        sync: false
